import { Timestamp } from 'firebase/firestore';
import { MockDocument } from '../types/mock';

export const SAMPLE_MOCKS: Omit<MockDocument, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    mockNumber: 1,
    exam: 'IBPS PO',
    testSeries: 'Testbook',
    testType: 'full',
    date: Timestamp.fromDate(new Date(Date.now() - 14 * 24 * 60 * 60 * 1000)),
    sections: {
      english: {
        questions: 30,
        attempted: 24,
        correct: 18,
        wrong: 6,
        unanswered: 6,
        marks: 16.5,
        timeSeconds: 1180,
      },
      numerical: {
        questions: 35,
        attempted: 22,
        correct: 19,
        wrong: 3,
        unanswered: 13,
        marks: 18.25,
        timeSeconds: 1200,
      },
      reasoning: {
        questions: 35,
        attempted: 26,
        correct: 23,
        wrong: 3,
        unanswered: 9,
        marks: 22.25,
        timeSeconds: 1190,
      },
    },
  },
  {
    mockNumber: 2,
    exam: 'IBPS PO',
    testSeries: 'Testbook',
    testType: 'full',
    date: Timestamp.fromDate(new Date(Date.now() - 11 * 24 * 60 * 60 * 1000)),
    sections: {
      english: {
        questions: 30,
        attempted: 26,
        correct: 21,
        wrong: 5,
        unanswered: 4,
        marks: 19.75,
        timeSeconds: 1150,
      },
      numerical: {
        questions: 35,
        attempted: 25,
        correct: 22,
        wrong: 3,
        unanswered: 10,
        marks: 21.25,
        timeSeconds: 1200,
      },
      reasoning: {
        questions: 35,
        attempted: 28,
        correct: 25,
        wrong: 3,
        unanswered: 7,
        marks: 24.25,
        timeSeconds: 1180,
      },
    },
  },
  {
    mockNumber: 3,
    exam: 'IBPS PO',
    testSeries: 'Testbook',
    testType: 'full',
    date: Timestamp.fromDate(new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)),
    sections: {
      english: {
        questions: 30,
        attempted: 27,
        correct: 23,
        wrong: 4,
        unanswered: 3,
        marks: 22.0,
        timeSeconds: 1140,
      },
      numerical: {
        questions: 35,
        attempted: 27,
        correct: 24,
        wrong: 3,
        unanswered: 8,
        marks: 23.25,
        timeSeconds: 1200,
      },
      reasoning: {
        questions: 35,
        attempted: 30,
        correct: 28,
        wrong: 2,
        unanswered: 5,
        marks: 27.5,
        timeSeconds: 1170,
      },
    },
  },
  {
    mockNumber: 4,
    exam: 'IBPS PO',
    testSeries: 'Testbook',
    testType: 'full',
    date: Timestamp.fromDate(new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)),
    sections: {
      english: {
        questions: 30,
        attempted: 28,
        correct: 24,
        wrong: 4,
        unanswered: 2,
        marks: 23.0,
        timeSeconds: 1120,
      },
      numerical: {
        questions: 35,
        attempted: 29,
        correct: 26,
        wrong: 3,
        unanswered: 6,
        marks: 25.25,
        timeSeconds: 1195,
      },
      reasoning: {
        questions: 35,
        attempted: 32,
        correct: 30,
        wrong: 2,
        unanswered: 3,
        marks: 29.5,
        timeSeconds: 1160,
      },
    },
  },
  {
    mockNumber: 5,
    exam: 'IBPS PO',
    testSeries: 'Testbook',
    testType: 'full',
    date: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    sections: {
      english: {
        questions: 30,
        attempted: 29,
        correct: 26,
        wrong: 3,
        unanswered: 1,
        marks: 25.25,
        timeSeconds: 1110,
      },
      numerical: {
        questions: 35,
        attempted: 31,
        correct: 28,
        wrong: 3,
        unanswered: 4,
        marks: 27.25,
        timeSeconds: 1190,
      },
      reasoning: {
        questions: 35,
        attempted: 33,
        correct: 31,
        wrong: 2,
        unanswered: 2,
        marks: 30.5,
        timeSeconds: 1150,
      },
    },
  },
];
